CREATE TABLE caixa( 
      id  integer generated by default as identity     NOT NULL , 
      data_lancamento date    NOT NULL , 
      valor float  (10,2)    NOT NULL , 
      historico varchar  (50)    NOT NULL , 
      banco varchar  (20)    NOT NULL , 
      status varchar  (20)    NOT NULL , 
      unidade varchar  (20)    NOT NULL , 
      created_at timestamp   , 
      updated_at timestamp   , 
      deleted_at timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE categoria( 
      id  integer generated by default as identity     NOT NULL , 
      categoria varchar  (50)   , 
 PRIMARY KEY (id)) ; 

 
 
  
